name: 'Setup NPMRC'
description: 'Sets up NPMRC for the public npm registry.'

inputs:
  github-token:
    description: 'the github token'
    required: true

outputs:
  auth-token:
    description: 'The generated NPM auth token'
    value: '${{ steps.npm_auth_token.outputs.auth-token }}'

runs:
  using: 'composite'
  steps:
    - name: 'Configure .npmrc'
      shell: 'bash'
      run: |-
        echo "@plaer1:registry=https://registry.npmjs.org" > ~/.npmrc
      env:
        INPUTS_GITHUB_TOKEN: '${{ inputs.github-token }}'
